compile: 
	g++ -std=c++0x -pthread src/main.cpp src/Ui.hpp src/Ui.cpp src/Fork.hpp src/Philosopher.cpp src/Philosopher.hpp src/Table.hpp src/Table.cpp -lncurses -Wall -Wextra -Wconversion -pedantic

run: 
	./a.out